# Generated by Django 4.2 on 2023-04-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productor',
            options={'ordering': ['nombre'], 'verbose_name': 'Productor', 'verbose_name_plural': 'Productores'},
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('productor_id', models.ManyToManyField(to='expediente.productor')),
            ],
            options={
                'verbose_name': 'Folio',
                'verbose_name_plural': 'Folios',
                'ordering': ['id'],
            },
        ),
    ]
