# Generated by Django 4.2 on 2023-04-27 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0002_alter_productor_options_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='folio',
            name='fecha_solicitud',
            field=models.DateTimeField(null=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AddField(
            model_name='productor',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.RemoveField(
            model_name='folio',
            name='productor_id',
        ),
        migrations.AlterField(
            model_name='productor',
            name='apell_mat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='apell_pat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='curp',
            field=models.CharField(max_length=18, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='genero',
            field=models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='productor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='folio',
            name='productor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expediente.productor'),
        ),
    ]
